/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_usbcam_pngcui_usbcamdemo_Jni */

#ifndef _Included_com_usbcam_pngcui_usbcamdemo_Jni
#define _Included_com_usbcam_pngcui_usbcamdemo_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_usbcam_pngcui_usbcamdemo_Jni
 * Method:    prepareCamera
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_usbcam_pngcui_usbcamdemo_Jni_prepareCamera
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_usbcam_pngcui_usbcamdemo_Jni
 * Method:    prepareCameraWithBase
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_usbcam_pngcui_usbcamdemo_Jni_prepareCameraWithBase
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_usbcam_pngcui_usbcamdemo_Jni
 * Method:    processCamera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_usbcam_pngcui_usbcamdemo_Jni_processCamera
  (JNIEnv *, jobject);

/*
 * Class:     com_usbcam_pngcui_usbcamdemo_Jni
 * Method:    stopCamera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_usbcam_pngcui_usbcamdemo_Jni_stopCamera
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_usbcam_pngcui_usbcamdemo_Jni_pixeltobmp
(JNIEnv *, jobject, jobject bitmap);

#ifdef __cplusplus
}
#endif
#endif
